name: Generate profile metrics

on:
  schedule:
    - cron: "15 3 * * *"
  workflow_dispatch:
  push:
    branches: [main]
    paths: [".github/workflows/metrics.yml"]

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: suzunn
          template: classic
          base: header
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Europe/Istanbul
          filename: metrics.svg
